# Generated by Django 4.2.3 on 2024-02-27 22:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage_personnel', '0003_alter_federationpersonel_dateadded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=255)),
                ('StartDate', models.DateTimeField(max_length=255)),
                ('EndDate', models.DateTimeField(max_length=255)),
                ('HostCity', models.CharField(max_length=255)),
                ('HostProvince', models.CharField(max_length=255)),
                ('ReportSubmitAgreement', models.BooleanField(default=False)),
                ('NumberOfTeam', models.IntegerField()),
                ('MethodOfSelection', models.CharField(max_length=255)),
                ('SelectionApprovedDate', models.DateField(max_length=255)),
                ('TravelDateTime', models.DateTimeField(max_length=255)),
                ('ModeOfTravel', models.CharField(max_length=255)),
                ('CodeOfConductAcceped', models.BooleanField(default=False)),
                ('RegulationsInterestDeclaration', models.CharField(default='NotProvided', max_length=300)),
                ('SelectionCriteriaProtocols', models.CharField(default='NotProvided', max_length=300)),
                ('GeneralRegulationSelectionProcedure', models.CharField(default='NotProvided', max_length=300)),
                ('DocumentationOfSelectionSubmitted', models.CharField(default='NotProvided', max_length=300)),
                ('TeamOfficialDuties', models.CharField(default='NotProvided', max_length=300)),
                ('AcceptanceOfTeamAppointment', models.CharField(default='NotProvided', max_length=300)),
                ('EventInvitation', models.CharField(default='NotProvided', max_length=300)),
                ('ApplicationDate', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 49, 49, 145541))),
                ('Step', models.CharField(default='start', max_length=255)),
                ('ApplicationStatus', models.CharField(default='Oncreate', max_length=255)),
                ('isHistory', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 49, 49, 145541))),
                ('DeclineReason', models.TextField(blank=True, null=True)),
                ('CancelReason', models.TextField(blank=True, null=True)),
                ('is_App_taking', models.BooleanField(default=False)),
                ('ApparelLetters', models.CharField(blank=True, max_length=300, null=True)),
                ('FederationPersonel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_personnel.federationpersonel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOfficial',
            fields=[
                ('TeamOfficialId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=100)),
                ('IDCopySubmited', models.BooleanField(default=False)),
                ('AcceptanceofTeamAppointment', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Represantative',
            fields=[
                ('RepresantativeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Event', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('RepresanativeLeve', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('IDCopySubmited', models.BooleanField(default=False)),
                ('AcceptanceofTeamAppointment', models.BooleanField(default=False)),
                ('RepresatativeType', models.CharField(default='Junior', max_length=255)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('FederationId', models.AutoField(primary_key=True, serialize=False)),
                ('FederationName', models.TextField()),
                ('HighPerformancePlan', models.CharField(default='NotProvided', max_length=300)),
                ('dateSelected', models.DateField(default=datetime.datetime(2024, 2, 28, 0, 49, 49, 144535))),
                ('year', models.IntegerField()),
                ('FederationEmail', models.TextField()),
                ('FederationPersonel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_personnel.federationpersonel')),
            ],
        ),
        migrations.CreateModel(
            name='FedDocuments',
            fields=[
                ('DocumentsId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('RegulationsInterestDeclaration', models.FileField(upload_to='MyApp/Docs')),
                ('SelectionCriteriaProtocols', models.FileField(upload_to='MyApp/Docs')),
                ('GeneralRegulationSelectionProcedure', models.FileField(upload_to='MyApp/Docs')),
                ('DocumentationOfSelectionSubmitted', models.FileField(upload_to='MyApp/Docs')),
                ('TeamOfficialDuties', models.FileField(upload_to='MyApp/Docs')),
                ('AcceptanceOfTeamAppointment', models.FileField(upload_to='MyApp/Docs')),
                ('HighPerformancePlan', models.FileField(upload_to='MyApp/Docs')),
                ('EventInvitation', models.FileField(upload_to='MyApp/Docs')),
                ('DateAdded', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 49, 49, 145541))),
                ('Year', models.CharField(default='2024', max_length=12)),
                ('FederationPersonel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_personnel.federationpersonel')),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('CommitteeMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Email', models.CharField(default='email', max_length=255)),
                ('PhoneNumber', models.CharField(default='number', max_length=255)),
                ('City', models.CharField(default='city', max_length=255)),
                ('Province', models.CharField(default='province', max_length=255)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('ApparelId', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(default='NotProvided', max_length=300)),
                ('DateAdded', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 49, 49, 146542))),
                ('Status', models.CharField(default='Approved', max_length=20)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 49, 49, 146542))),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
