# Generated by Django 4.2.3 on 2023-11-16 10:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationId', models.AutoField(primary_key=True, serialize=False)),
                ('EventName', models.CharField(max_length=255)),
                ('StartDate', models.DateTimeField(max_length=255)),
                ('EndDate', models.DateTimeField(max_length=255)),
                ('HostCity', models.CharField(max_length=255)),
                ('HostProvince', models.CharField(max_length=255)),
                ('ReportSubmitAgreement', models.BooleanField(default=False)),
                ('NumberOfTeam', models.IntegerField()),
                ('MethodOfSelection', models.CharField(max_length=255)),
                ('SelectionApprovedDate', models.DateField(max_length=255)),
                ('TravelDateTime', models.DateTimeField(max_length=255)),
                ('ModeOfTravel', models.CharField(max_length=255)),
                ('CodeOfConductAcceped', models.BooleanField(default=False)),
                ('RegulationsInterestDeclaration', models.CharField(default='NotProvided', max_length=300)),
                ('SelectionCriteriaProtocols', models.CharField(default='NotProvided', max_length=300)),
                ('GeneralRegulationSelectionProcedure', models.CharField(default='NotProvided', max_length=300)),
                ('DocumentationOfSelectionSubmitted', models.CharField(default='NotProvided', max_length=300)),
                ('TeamOfficialDuties', models.CharField(default='NotProvided', max_length=300)),
                ('AcceptanceOfTeamAppointment', models.CharField(default='NotProvided', max_length=300)),
                ('HighPerformancePlan', models.CharField(default='NotProvided', max_length=300)),
                ('EventInvitation', models.CharField(default='NotProvided', max_length=300)),
                ('ApplicationDate', models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 4, 49, 204230))),
                ('Step', models.CharField(default='start', max_length=255)),
                ('ApplicationStatus', models.CharField(default='Oncreate', max_length=255)),
                ('isHistory', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(default=datetime.datetime(2023, 11, 16, 12, 4, 49, 204230))),
                ('DeclineReason', models.TextField(blank=True, null=True)),
                ('CancelReason', models.TextField(blank=True, null=True)),
                ('ApparelLetters', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOfficial',
            fields=[
                ('TeamOfficialId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=100)),
                ('IDCopySubmited', models.BooleanField(default=False)),
                ('AcceptanceofTeamAppointment', models.BooleanField(default=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Represantative',
            fields=[
                ('RepresantativeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Event', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('RepresanativeLeve', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('IDCopySubmited', models.BooleanField(default=False)),
                ('AcceptanceofTeamAppointment', models.BooleanField(default=False)),
                ('RepresatativeType', models.CharField(default='Junior', max_length=255)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
        migrations.CreateModel(
            name='FederationPersonel',
            fields=[
                ('PersonelId', models.AutoField(primary_key=True, serialize=False)),
                ('FederationName', models.CharField(blank=True, max_length=255, null=True)),
                ('PersonelPhone', models.CharField(max_length=255)),
                ('PersonelGender', models.CharField(blank=True, max_length=6, null=True)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('CommitteeMemberId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Email', models.CharField(default='email', max_length=255)),
                ('PhoneNumber', models.CharField(default='number', max_length=255)),
                ('City', models.CharField(default='city', max_length=255)),
                ('Province', models.CharField(default='province', max_length=255)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='FederationPersonel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.federationpersonel'),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
