# Generated by Django 4.2.3 on 2023-07-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('ApplicationId', models.AutoField(primary_key=True, serialize=False)),
                ('ApplicationStatus', models.CharField(max_length=255)),
                ('EventName', models.CharField(max_length=255)),
                ('StartDate', models.DateTimeField(max_length=255)),
                ('EndDate', models.DateTimeField(max_length=255)),
                ('HostCity', models.CharField(max_length=255)),
                ('HostProvince', models.CharField(max_length=255)),
                ('RepresatativeType', models.CharField(max_length=255)),
                ('ReportSubmitAgreement', models.BooleanField(default=False)),
                ('NumberOfTeam', models.IntegerField(max_length=255)),
                ('MethodOfSelection', models.CharField(max_length=255)),
                ('SelectionApprovedDate', models.DateField(max_length=255)),
                ('TravelDateTime', models.DateTimeField(max_length=255)),
                ('ModeOfTravel', models.CharField(max_length=255)),
            ],
        ),
    ]
