# Generated by Django 4.2.3 on 2023-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Represantative',
            fields=[
                ('RepresantativeId', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Event', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('RepresanativeLeve', models.CharField(max_length=255)),
                ('Duration', models.CharField(max_length=255)),
                ('IDCopySiubmited', models.TextField(default='null')),
                ('AcceptanceofTeamAppointment', models.TextField(default='null')),
            ],
        ),
    ]
