# Generated by Django 4.2.3 on 2023-11-23 00:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_federationpersonel_dateselected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 2, 44, 8, 926296)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 2, 44, 8, 926296)),
        ),
        migrations.AlterField(
            model_name='federationpersonel',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2023, 11, 23, 2, 44, 8, 926296)),
        ),
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('ApparelId', models.AutoField(primary_key=True, serialize=False)),
                ('letter', models.CharField(default='NotProvided', max_length=300)),
                ('DateAdded', models.DateTimeField(default=datetime.datetime(2023, 11, 23, 2, 44, 8, 926296))),
                ('Status', models.CharField(default='Approved', max_length=20)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
            ],
        ),
    ]
