# Generated by Django 4.2.3 on 2023-07-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_represantative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='represantative',
            name='RepresantativeId',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
