# Generated by Django 4.2.3 on 2023-07-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_alter_represantative_represantativeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='represantative',
            name='RepresantativeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
