# Generated by Django 4.2.3 on 2023-11-24 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_apparel_user_alter_apparel_dateadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 12, 10, 16, 628557)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 12, 10, 16, 628557)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 12, 10, 16, 628557)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 12, 10, 16, 628557)),
        ),
        migrations.AlterField(
            model_name='federationpersonel',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 12, 10, 16, 628557)),
        ),
    ]
