# Generated by Django 4.2.3 on 2023-08-10 11:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyApp', '0006_selctionofcommittee'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='AcceptanceOfTeamAppointment',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 13, 11, 15, 916963)),
        ),
        migrations.AddField(
            model_name='application',
            name='CodeOfConductAcceped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='DocumentationOfSelectionSubmitted',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='GeneralRegulationSelectionProcedure',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='HighPerformancePlan',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='InvitationOfNationalEvent',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='RegulationsInterestDeclaration',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='SelectionCriteriaProtocols',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='TeamOfficialDuties',
            field=models.CharField(default='NotProvided', max_length=300),
        ),
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationStatus',
            field=models.CharField(default='Oncreate', max_length=255),
        ),
        migrations.AlterField(
            model_name='represantative',
            name='AcceptanceofTeamAppointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='represantative',
            name='IDCopySiubmited',
            field=models.BooleanField(default=False),
        ),
    ]
