# Generated by Django 4.2.3 on 2023-08-10 11:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_application_acceptanceofteamappointment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeMember',
            fields=[
                ('MemberId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOfficial',
            fields=[
                ('TeamOfficialId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=30)),
                ('Designation', models.CharField(max_length=100)),
                ('IDCopySubmited', models.BooleanField(default=False)),
                ('AcceptanceofTeamAppointment', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='SelctionOfCommittee',
        ),
        migrations.AddField(
            model_name='represantative',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 10, 13, 54, 21, 680039)),
        ),
        migrations.AddField(
            model_name='teamofficial',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application'),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application'),
        ),
    ]
