# Generated by Django 5.0.2 on 2024-03-14 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_committeemember_id_number_represantative_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='status',
            field=models.CharField(default='OnCreate', max_length=30),
        ),
        migrations.AddField(
            model_name='represantative',
            name='status',
            field=models.CharField(default='OnCreate', max_length=30),
        ),
        migrations.AddField(
            model_name='teamofficial',
            name='status',
            field=models.CharField(default='OnCreate', max_length=30),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 658691)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 658691)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 658691)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 658691)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 658691)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 656176)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 656176)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 14, 51, 56, 656176)),
        ),
    ]
