# Generated by Django 4.2.3 on 2024-02-21 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_feddocuments_alter_apparel_dateadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_App_taking',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 17, 5, 25, 264353)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 17, 5, 25, 264353)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 17, 5, 25, 264353)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 17, 5, 25, 264353)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 17, 5, 25, 264353)),
        ),
        migrations.AlterField(
            model_name='federationpersonel',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 2, 21, 17, 5, 25, 264353)),
        ),
    ]
