# Generated by Django 4.1.2 on 2023-08-15 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0009_remove_application_represatativetype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='represantative',
            old_name='IDCopySiubmited',
            new_name='IDCopySubmited',
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 9, 20, 6, 492158)),
        ),
    ]
