# Generated by Django 4.1.2 on 2023-08-15 07:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_rename_idcopysiubmited_represantative_idcopysubmited_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 9, 30, 16, 565096)),
        ),
        migrations.AlterField(
            model_name='represantative',
            name='RepresantativeId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
