# Generated by Django 4.1.2 on 2023-08-15 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_application_applicationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 11, 40, 41, 218433)),
        ),
        migrations.AlterField(
            model_name='represantative',
            name='RepresantativeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
