# Generated by Django 4.1.2 on 2023-08-15 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_alter_application_applicationdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='City',
            field=models.CharField(default='city', max_length=255),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='Email',
            field=models.CharField(default='email', max_length=255),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='PhoneNumber',
            field=models.CharField(default='number', max_length=255),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='Province',
            field=models.CharField(default='province', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 16, 44, 21, 231763)),
        ),
    ]
