# Generated by Django 5.0.2 on 2024-03-14 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_committeemember_is_terms_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamofficial',
            name='Email',
            field=models.CharField(default='email', max_length=255),
        ),
        migrations.AddField(
            model_name='teamofficial',
            name='PhoneNumber',
            field=models.CharField(default='number', max_length=255),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 14, 17, 59, 21, 384253)),
        ),
    ]
