# Generated by Django 4.1.2 on 2023-08-15 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_committeemember_city_committeemember_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='MemberId',
            new_name='CommitteeMemberId',
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 16, 47, 35, 110737)),
        ),
    ]
