# Generated by Django 4.1.2 on 2023-08-15 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0016_alter_application_applicationdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='Name',
            new_name='FirstName',
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 16, 51, 0, 370159)),
        ),
    ]
