# Generated by Django 4.1.2 on 2023-08-16 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0017_rename_name_committeemember_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='InvitationOfNationalEvent',
            new_name='EventInvitation',
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 18, 17, 45, 464239)),
        ),
    ]
