# Generated by Django 4.1.2 on 2023-08-22 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0018_rename_invitationofnationalevent_application_eventinvitation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 14, 13, 17, 999543)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationStatus',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
