# Generated by Django 4.1.2 on 2023-08-22 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0019_alter_application_applicationdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 22, 14, 16, 39, 725299)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationStatus',
            field=models.CharField(default='Oncreate', max_length=255),
        ),
    ]
