# Generated by Django 5.0.2 on 2024-03-19 07:29

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0020_remove_committeemember_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 559352)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 559352)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 558353)),
        ),
        migrations.AlterField(
            model_name='application',
            name='Committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='MyApp.committeemember'),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 558353)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 557352)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 556353)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 556353)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 9, 29, 22, 556353)),
        ),
    ]
