# Generated by Django 4.2.3 on 2023-08-25 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_application_step_alter_application_applicationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 25, 11, 1, 18, 788940)),
        ),
    ]
