# Generated by Django 5.0.2 on 2024-03-19 13:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0025_committeemember_is_history_alter_apparel_dateadded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeemember',
            name='year',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 592195)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 592195)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 591195)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 591195)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='RequestDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 591195)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 591195)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 590193)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 590193)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 19, 15, 31, 55, 590193)),
        ),
    ]
