# Generated by Django 5.0.2 on 2024-04-26 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_represantative_federationpersonel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='LateAppMotivation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 984827)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 984827)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 984827)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 984827)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='RequestDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 979813)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='ResponseDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 979813)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 979813)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 979813)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 979813)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 1, 39, 12, 979813)),
        ),
    ]
