# Generated by Django 5.0.2 on 2024-05-04 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_application_is_lateapplication_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='DocumentationOfSelectionSubmitted',
        ),
        migrations.RemoveField(
            model_name='application',
            name='GeneralRegulationSelectionProcedure',
        ),
        migrations.RemoveField(
            model_name='application',
            name='ModeOfTravel',
        ),
        migrations.RemoveField(
            model_name='application',
            name='RegulationsInterestDeclaration',
        ),
        migrations.RemoveField(
            model_name='application',
            name='SelectionCriteriaProtocols',
        ),
        migrations.RemoveField(
            model_name='application',
            name='TeamOfficialDuties',
        ),
        migrations.RemoveField(
            model_name='feddocuments',
            name='EventInvitation',
        ),
        migrations.RemoveField(
            model_name='federation',
            name='HighPerformancePlan',
        ),
        migrations.AddField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='RequestDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='ResponseDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 4, 14, 7, 19, 734640)),
        ),
    ]
