# Generated by Django 5.0.2 on 2024-05-05 20:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_represantative_represatativelevel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='RequestDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='ResponseDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 26, 29, 402624)),
        ),
        migrations.CreateModel(
            name='SportsPerson',
            fields=[
                ('SportsPersonId', models.AutoField(primary_key=True, serialize=False)),
                ('Id_number', models.CharField(blank=True, max_length=13, null=True)),
                ('FirstName', models.CharField(max_length=255)),
                ('Surname', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('PhoneNumber', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=255)),
                ('Province', models.CharField(max_length=255)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('RepresanativeLeve', models.CharField(default='1', max_length=255)),
                ('IDCopySubmited', models.BooleanField(default=False)),
                ('AcceptanceofTeamAppointment', models.BooleanField(default=False)),
                ('RepresatativeType', models.CharField(default='Athlete', max_length=50)),
                ('RepresatativeLevel', models.CharField(default='Junior', max_length=50)),
                ('is_IdNumberValidated', models.BooleanField(default=False)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_terms_accepted', models.BooleanField(default=False)),
                ('status', models.CharField(default='OnCreate', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicantApplication',
            fields=[
                ('ApplicantApplicationId', models.AutoField(primary_key=True, serialize=False)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.application')),
                ('SportsPerson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyApp.sportsperson')),
            ],
        ),
        migrations.DeleteModel(
            name='Represantative',
        ),
    ]
