# Generated by Django 5.0.2 on 2024-05-05 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0032_alter_apparel_dateadded_alter_apparel_datecreated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsperson',
            name='is_terms_accepted',
        ),
        migrations.AddField(
            model_name='applicantapplication',
            name='is_terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='RequestDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='ResponseDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 460499)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 459577)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 459063)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 459063)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 32, 29, 459063)),
        ),
    ]
