# Generated by Django 5.0.2 on 2024-05-05 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0034_rename_application_applicantapplication_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='RequestDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='ResponseDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 210665)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 209832)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 208822)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 208822)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 22, 35, 49, 208822)),
        ),
    ]
