# Generated by Django 5.0.2 on 2024-05-15 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0038_remove_sportsperson_represatativelevel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='committeemember',
            old_name='is_terms_accepted',
            new_name='is_Chairperson',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='RequestDate',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='ResponseDate',
        ),
        migrations.RemoveField(
            model_name='committeemember',
            name='year',
        ),
        migrations.AddField(
            model_name='committeemember',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AddField(
            model_name='committeemember',
            name='position',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='City',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='Province',
            field=models.CharField(default='KwaZulu-Natal', max_length=255),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 13, 15, 14, 854356)),
        ),
    ]
