# Generated by Django 5.0.2 on 2024-05-15 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0039_rename_is_terms_accepted_committeemember_is_chairperson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='City',
            field=models.CharField(default='city', max_length=255),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 14, 54, 7, 497651)),
        ),
    ]
