# Generated by Django 5.0.2 on 2024-05-15 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0040_alter_apparel_dateadded_alter_apparel_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantapplication',
            name='declineReason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='apparel',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicantsClosingDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='application',
            name='ApplicationDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='application',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='committeemember',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='feddocuments',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='dateSelected',
            field=models.DateField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_approved',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
        migrations.AlterField(
            model_name='federation',
            name='date_requested',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 15, 21, 14, 0, 608918)),
        ),
    ]
