# Generated by Django 4.2.3 on 2024-02-27 22:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FederationPersonel',
            fields=[
                ('PersonelId', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('id_number', models.CharField(max_length=13)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('email', models.TextField()),
                ('Phone', models.CharField(blank=True, max_length=255, null=True)),
                ('Status', models.CharField(default='Pending', max_length=20)),
                ('DateAdded', models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 40, 56, 250596))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
