# Generated by Django 4.2.3 on 2024-02-27 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='federationpersonel',
            name='DateAdded',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 0, 46, 47, 490654)),
        ),
    ]
